### PR TITLE
Feature/ros integration

### PR DESCRIPTION
**Pull request by gocarlos**
created a first version of the working ros binding prototype.

### CODE REVIEW

**Review by nidegen — APPROVED** [review]
good to merge for me. didnt go too much into details, but i wonder if we should not adapt the overall architecture. we need to discuss this thursday.

**Comment by nidegen** [comment]
ie. i would maybe do, like wrapper/ios, a wrapper/ros dir where all ros stuff goes into

**Comment by gocarlos** [comment]
@nidegen yes, this sounds like a good idea :)

Let me address that later in a separate PR.

**Comment by gocarlos** [comment]
@nidegen please do not remove this branch :)

**Pull request merged**
