### PR TITLE
Feature/ros integration

### PR DESCRIPTION
**Pull request by gocarlos**
Further ROS integration and implementation of the topic discussed yesterday

### CODE REVIEW

**Comment by gocarlos** [comment]
removing this branch after merging, as it seems to have some errors.

**Review by nidegen — APPROVED** [review]
awesome work!

**Comment by nidegen** [comment]
how you mean 'removing branch as it seems to have errors'? what kind of errors?

**Comment by gocarlos** [comment]
Had some merge conflicts when merging master back to this branch

**Pull request merged**
