### PR TITLE
Wip/style improvements

### PR DESCRIPTION
**Pull request by gocarlos**
With this PR the following points are addressed: 
- CI added
- google style format file added
- skeleton of the wrapper class added
- sample unit tests added

### CODE REVIEW

**Comment by nidegen** [comment]
in case you dont have a strong opinion otherwise, i would stick to google styleguide:)

source file of [Class named FooClass would be foo-class.cc with header foo-class.h](https://google.github.io/styleguide/cppguide.html#File_Names)

and also use [// for comments only instead of /**/](https://google.github.io/styleguide/cppguide.html#Comment_Style)

**Comment by gocarlos** [comment]
I'll do that. 

regarding the comments: I'd like later to eventually document the code, Doxygen uses the comments in the source code for that. Do you have another tool in mind?
http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html

I'll implement the comments for now as you said, but we should agree on some comment syntax that also works with documenting software :)

We should also make some kind of template for the beginning of the source code files

**Comment by gocarlos** [comment]
@nidegen do you have any other suggestions before merging?

**Comment by nidegen** [comment]
i made googletest a submodule:)

**Comment by nidegen** [comment]
be sure to squash and merge so that all google test files are not added to the history:)

**Pull request merged**
